name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy-infrastructure:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Webserver)
        run: terraform init -reconfigure
        working-directory: terraform/webserver

      - name: Terraform Destroy (Webserver)
        run: terraform destroy --auto-approve
        working-directory: terraform/webserver

      - name: Terraform Init (Network)
        run: terraform init -reconfigure
        working-directory: terraform/network

      - name: Terraform Destroy (Network)
        run: terraform destroy --auto-approve
        working-directory: terraform/network